sudo: required

services:
  - docker

before_install:
  - docker pull moussavdb/build-java
  - docker run -d moussavdb/build-java mvn -V -s settings.xml clean install

script:
  - mvn -V -s settings.xml clean install
